/*
 * GeometryManifest — a flat, fully-explicit description of a detector geometry.
 *
 * Produced and consumed by the generic "manifest seam" pipeline: a
 * GeometryManifest is the contract between Julia DetectorSpec code that
 * lays out the geometry and the C++ PlaceManifest interpreter that
 * realises it via GODDESS primitive constructors.
 *
 * A GeometryManifest is produced either by DetectorConstruction::BuildManifest_*
 * (from a hard-coded named setup) or by ManifestFile::Read (from a file,
 * eventually generated by the Julia DetectorSpec layer), and is consumed by
 * DetectorConstruction::PlaceManifest, which places every element by calling the
 * existing GODDESS primitive constructors.
 *
 * Volumes reference each other by `name` (a manifest-internal id); the reserved
 * id "world" denotes the world volume.
 *
 * The geometry is a SINGLE ORDERED LIST of placement entries
 * (GeometryManifest::placements). PlaceManifest places them in exactly that
 * order. Order is geometry-critical: GODDESS ConstructWrapping (with no explicit
 * cut-list) subtracts every physical volume that exists at call time, so a
 * wrapping must be placed at the exact point in the sequence where the legacy
 * code constructed it. Each placement is a scintillator, a fibre, a wrapping, or
 * a SiPM (PlacementEntry::kind). The casing (aluminum box + lead sheet) is always
 * placed last and is carried separately.
 *
 * All quantities are stored in Geant4 internal units (mm for lengths, radian
 * for angles), so ManifestFile is a pure double (de)serialiser with no unit logic.
 */

#ifndef GEOMETRYMANIFEST_HH_
#define GEOMETRYMANIFEST_HH_

#include <vector>
#include <cmath>
#include <G4String.hh>
#include <G4ThreeVector.hh>


/// A scintillator tile. Its wrapping (if any) is a separate WrapEntry.
struct ScintEntry
{
	G4String       name;            ///< manifest ref-id
	G4String       g4name;          ///< GODDESS SetScintillatorName arg ("" = don't call)
	G4ThreeVector  dims;            ///< full dimensions (x,y,z)
	G4ThreeVector  pos;             ///< translation relative to the mother volume
	G4double       rot[9];          ///< rotation matrix, row-major (identity if unset)
	G4String       mother;          ///< ref-id of the mother volume ("world" = world)
	G4String       material_file;   ///< scintillator property file
	G4bool         sensitive;       ///< ConstructASensitiveDetector() is to be called

	ScintEntry()
	: sensitive(false)
	{
		rot[0] = 1; rot[1] = 0; rot[2] = 0;
		rot[3] = 0; rot[4] = 1; rot[5] = 0;
		rot[6] = 0; rot[7] = 0; rot[8] = 1;
	}
};


/// A single fibre segment (straight or circular arc).
struct FiberEntry
{
	G4String       name;            ///< manifest ref-id
	G4String       kind;            ///< "straight" or "bent"
	G4String       mother;          ///< ref-id of the mother volume ("world" = world)
	G4ThreeVector  start;           ///< start point relative to the reference volume
	G4ThreeVector  end;             ///< end point relative to the reference volume
	G4double       bend_angle;      ///< bending delta angle (bent only)
	G4ThreeVector  bend_axis;       ///< bending axis (bent only)
	G4String       material_file;   ///< fibre property file

	G4String       reference;       ///< SetFibreReferenceVolume ref-id ("" = not called)
	G4bool         glued;           ///< SetFibreGlued() is to be called
	G4String       glue_file;       ///< glue property file
	G4String       glue_profile;    ///< embedment profile ("round" / "quadratic")
	G4double       start_reflectivity;///< SetFibreStartPointReflectivity (NaN = not called)
	G4double       end_reflectivity;///< SetFibreEndPointReflectivity (NaN = not called)

	G4int          loop_id;         ///< loop-length accounting bucket (-1 = print individually)

	FiberEntry()
	: kind("straight"), bend_angle(0.), bend_axis(G4ThreeVector(0, 0, 0)),
	  glued(false), start_reflectivity(NAN), end_reflectivity(NAN), loop_id(-1)
	{}
};


/// A reflective wrapping around a scintillator tile.
struct WrapEntry
{
	G4String               scint;          ///< ref-id of the scintillator tile to wrap
	G4String               g4name;         ///< GODDESS SetWrappingName arg ("" = don't call)
	G4String               material_file;  ///< wrapping property file
	std::vector<G4String>  cut;            ///< explicit cut-volume candidates (empty = auto-derive from this tile's fibres)
};


/// A SiPM photon detector plus its optical coupling to a fibre.
struct SipmEntry
{
	G4String       name;
	G4String       ref_volume;      ///< ref-id of the reference volume
	G4ThreeVector  face_dir;        ///< sensitive-face direction
	G4ThreeVector  rel_pos;         ///< position relative to the reference volume
	G4double       edge_length;
	G4String       fiber;           ///< ref-id of the coupled fibre
	G4ThreeVector  coupling_normal;
	G4ThreeVector  coupling_pos;
	G4double       coupling_width;
	G4bool         fiber_is_base;

	SipmEntry()
	: edge_length(0.), coupling_width(0.), fiber_is_base(true)
	{}
};


/// One element placement. The active member is selected by `kind`.
struct PlacementEntry
{
	enum Kind { SCINT, FIBER, WRAP, SIPM };

	Kind        kind;
	ScintEntry  scint;
	FiberEntry  fiber;
	WrapEntry   wrap;
	SipmEntry   sipm;

	PlacementEntry() : kind(SCINT) {}

	static PlacementEntry Scint(const ScintEntry& s)
	{ PlacementEntry p; p.kind = SCINT; p.scint = s; return p; }

	static PlacementEntry Fiber(const FiberEntry& f)
	{ PlacementEntry p; p.kind = FIBER; p.fiber = f; return p; }

	static PlacementEntry Wrap(const WrapEntry& w)
	{ PlacementEntry p; p.kind = WRAP; p.wrap = w; return p; }

	static PlacementEntry Sipm(const SipmEntry& s)
	{ PlacementEntry p; p.kind = SIPM; p.sipm = s; return p; }
};


/// The outer aluminum box + lead sheet, derived from the module bounding box.
struct CasingSpec
{
	G4double  module_half_x;
	G4double  module_min_y;
	G4double  module_max_y;
	G4double  module_half_z;
	G4double  aluminum_thickness;   ///< <= 0 disables the aluminum box
	G4double  lead_thickness;       ///< <= 0 disables the lead sheet
	G4int     num_bars;             ///< lead-sheet half-width input
	G4double  bar_width;            ///< lead-sheet half-width input
	G4double  scinti_z;             ///< lead-sheet half-depth input

	CasingSpec()
	: module_half_x(0.), module_min_y(0.), module_max_y(0.), module_half_z(0.),
	  aluminum_thickness(0.), lead_thickness(0.),
	  num_bars(0), bar_width(0.), scinti_z(0.)
	{}
};


/// A complete, flat detector geometry: one ordered placement list + casing.
struct GeometryManifest
{
	G4String                     setup_label;   ///< informational, e.g. "B1"
	std::vector<PlacementEntry>  placements;    ///< exact construction order
	CasingSpec                   casing;        ///< placed last
};

#endif // GEOMETRYMANIFEST_HH_
